version: 2.1
jobs:
  build:
    machine:
      image: android:2024.01.1
    steps:
      - checkout
      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: fn-aimbot.apk
workflows:
  build:
    jobs:
      - build
